# Generated by Django 3.2.5 on 2021-08-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='pstalCode',
            new_name='postalCode',
        ),
    ]
